#ifndef GIMBAL_CONFIG_H
#define GIMBAL_CONFIG_H



#define GIMBAL_PITCH_OFFSET_RAD 0.0f;

#define GIMBAL_PITCH_ZEROANGLE_RAD 0.225f;

#define GIMBAL_YAW_OFFSET_RAD 3.07179666f;

#define GIMBAL_AI_IMU_BACKUP 0   // 1 = 启用备用 IMU(世界系) 控制

#define PITCH_OFFSET_RAD 0.0f;
#define ROLL_OFFSET_RAD 0.0f;

#define JCOM_DEBUG_PORT PYRO_UART1

#endif
